/**
 * PWA / favicon generator — the logo mark is the single source (→ plan 11).
 *
 *   npm run icons
 *
 * Everything the app wears in a launcher, a browser tab or a lock screen is
 * produced here from one file, `src/lib/assets/logo-mark.svg` (the design's
 * mark 13b: a white house + two peach sparkles). The identity therefore lives
 * in exactly one place; re-run this after editing the mark and commit the
 * outputs.
 *
 * Outputs (committed):
 *   static/icons/icon-192.png  · icon-512.png            app icon, full-bleed sage   (purpose: any)
 *   static/icons/icon-192-maskable.png · -512-maskable   extra safe-zone padding     (purpose: maskable)
 *   static/icons/apple-touch-icon.png (180)              iOS home screen, no alpha
 *   static/icons/favicon-96.png                          PNG tab-icon fallback
 *   static/icons/badge-72.png                            Android status-bar silhouette (alpha-only)
 *   static/favicon.svg                                   the browser-tab mark (rounded tile)
 *
 * Standalone by design (like scripts/seed.ts): no $lib/$env virtual modules, so
 * it runs under Node's native TypeScript support without Vite.
 */
import sharp from 'sharp';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const MARK_SVG = join(root, 'src/lib/assets/logo-mark.svg');
const ICONS_DIR = join(root, 'static/icons');
const FAVICON_SVG = join(root, 'static/favicon.svg');

/**
 * The logo's own colours — these belong to the mark, not the design-token
 * palette (a token is a var(); a rasterised PNG can hold no such thing).
 * `--sage` #5F8D72 is the tile; the white house and peach sparkles live in the
 * SVG itself.
 */
const SAGE = { r: 0x5f, g: 0x8d, b: 0x72, alpha: 1 };

const markSource = readFileSync(MARK_SVG, 'utf8');

/**
 * The mark, rasterised transparent at an exact pixel size. Giving the SVG root
 * px dimensions (it declares 60×60 with a matching viewBox) makes librsvg
 * render the vector *at* that resolution rather than at 96dpi and scaling —
 * i.e. crisp edges on the white house stroke at every size.
 */
function markAt(px: number): Promise<Buffer> {
	const svg = markSource.replace('width="60" height="60"', `width="${px}" height="${px}"`);
	return sharp(Buffer.from(svg)).png().toBuffer();
}

/**
 * A sage tile with the mark centred on it, flattened to fully opaque (no alpha
 * channel — iOS fills a transparent app icon with black, and there is nothing
 * to be transparent *to* anyway). `ratio` is the mark's share of the canvas.
 */
async function tile(size: number, ratio: number): Promise<Buffer> {
	const mark = await markAt(Math.round(size * ratio));
	return sharp({ create: { width: size, height: size, channels: 4, background: SAGE } })
		.composite([{ input: mark, gravity: 'center' }])
		.flatten({ background: SAGE })
		.png({ compressionLevel: 9 })
		.toBuffer();
}

/**
 * The Android notification badge: a solid white house on transparent, tightly
 * framed. Android keeps only the alpha channel and tints the silhouette itself,
 * so the sparkles (noise at 24dp) are dropped and the colour is irrelevant.
 */
async function badge(size: number): Promise<Buffer> {
	const px = Math.round(size * 0.66);
	// A viewBox cropped to the house (x 12–42, y 19–49) so it sits centred,
	// rather than low-left where it lives inside the full 60-box beside the
	// sparkles.
	const house = `<svg xmlns="http://www.w3.org/2000/svg" width="${px}" height="${px}" viewBox="9 16 36 36"><path d="M12 33 L27 19 L42 33 V46 a3 3 0 0 1 -3 3 H15 a3 3 0 0 1 -3 -3 Z" fill="#fff"/></svg>`;
	const shape = await sharp(Buffer.from(house)).png().toBuffer();
	return sharp({
		create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } }
	})
		.composite([{ input: shape, gravity: 'center' }])
		.png({ compressionLevel: 9 })
		.toBuffer();
}

/** The mark's paths, lifted out of the source svg wrapper for re-use in the favicon. */
function markInner(): string {
	const match = markSource.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
	if (!match) throw new Error(`could not read the mark out of ${MARK_SVG}`);
	return match[1].trim();
}

/**
 * A rounded sage tile with the mark scaled up slightly to read at 16px. Kept as
 * SVG (crisp at any tab size, and a modern favicon should be one) with a PNG
 * fallback beside it for the browsers that still want raster.
 */
function faviconSvg(): string {
	const inner = markInner()
		.split('\n')
		.map((line) => `\t\t${line.trim()}`)
		.join('\n');
	return `<!-- Choreganized favicon — generated by scripts/icons.ts from logo-mark.svg. Do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 60 60" fill="none">
	<rect width="60" height="60" rx="13" fill="#5F8D72" />
	<g transform="translate(30 30) scale(1.1) translate(-30 -30)">
${inner}
	</g>
</svg>
`;
}

async function main() {
	mkdirSync(ICONS_DIR, { recursive: true });

	const outputs: Array<[string, Buffer]> = [
		// App icon (purpose: any) — full-bleed sage, mark at the design's ~60% share.
		['icon-192.png', await tile(192, 0.6)],
		['icon-512.png', await tile(512, 0.6)],
		// Maskable — the mark pulled in so it clears the 80%-diameter safe circle
		// under any launcher's mask; the sage bleeds to the edge and is safe to clip.
		['icon-192-maskable.png', await tile(192, 0.52)],
		['icon-512-maskable.png', await tile(512, 0.52)],
		// iOS home screen — square, opaque; iOS applies its own rounding.
		['apple-touch-icon.png', await tile(180, 0.58)],
		// A fuller tile for the raster favicon fallback (reads better small).
		['favicon-96.png', await tile(96, 0.66)],
		// Notification status-bar glyph.
		['badge-72.png', await badge(72)]
	];

	for (const [name, buffer] of outputs) {
		writeFileSync(join(ICONS_DIR, name), buffer);
		console.log(`  static/icons/${name}  (${(buffer.length / 1024).toFixed(1)} KB)`);
	}

	writeFileSync(FAVICON_SVG, faviconSvg());
	console.log('  static/favicon.svg');

	console.log(`\nGenerated ${outputs.length + 1} icon file(s) from src/lib/assets/logo-mark.svg`);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
